jndi-name = jdbc/oidb
sql-table = oidb

# one of the next three url will be used depending on repo/status metadata
tap-baseurl-stable=http://tap.jmmc.fr/vollt/tap/
tap-baseurl-beta=http://tap-preprod.jmmc.fr/vollt/tap/
tap-baseurl-alpha=http://tapserver:8080/vollt/tap

